# 모듈 메모장
# 써다보면 손이 기억함
# 외우려고 안해도됨

# debug: 화면에 메시지 출력 또는 디버깅용

# msg: 화면 출력
- debug:
    msg: "현재 OS는 {{ ansible_os_family }}"


# var: 변수 내용 그대로 출력
- debug:
    var: disk_result.stdout


# 단순 명령어 실행
# # command: cat /etc/passwd | grep root, &> /dev/null ← 이거 안 됨
# shell 사용 시 shell 모듈 써야함
- command: df -h /
  register: disk_result


# http 프로토콜 메서드 사용 모듈
- uri:
    url: http://10.0.2.12:5000/health
    method: GET
    status_code: 200
  register: health

#-------------------------------------------------------------------------------------------
# 파티션/LVM 생성 -> 마운트 -> 파일시스템

# 파티션 생성 모듈
- parted:
    device: /dev/sdb
    number: 1
    state: present
    part_start: 0%
    part_end: 100%
    label: gpt


# VG 모듈, PV는 자동생성
- lvg:
    vg: my_vg
    pvs: /dev/sdb1

# LV 모듈
- lvol:
    vg: my_vg
    lv: my_lv
    size: 5G

#  파일시스템 모듈
- filesystem:
    fstype: xfs
    dev: /dev/my_vg/my_lv


# 마운트 모듈
- mount:
    path: /mnt/data
    src: /dev/my_vg/my_lv
    fstype: xfs
    state: mounted


#-------------------------------------------------------------------------------------------